@startuml UpdateAsync
skinparam {
    monoChrome false
    rectangleRoundCorner 15
    rectangleBackgroundColor #smokewithe
}

rectangle "TEntity UpdateAsync(TEntity entity)" { 
    start
    if (ACCOUNT_ON?) then (yes)
        :CheckAuthorizationAsync(type, "UpdateAsync");
    else (no)
    endif
    :result = ExecuteUpdateAsync(entity);
    :return BeforeReturn(result);
    stop
}
@enduml
Update